### ISSUE TITLE
Installation instructions incomplete

### ISSUE THREAD

**Issue by amedee** [msiemens/PyGitUp#20]
The installation instructions are incomplete.

On Ubuntu 14.10:
```
$ sudo pip install git-up
sudo: pip: command not found
```
You need to install python-pip first (not installed by default):
```
sudo apt-get install -y python-pip
```
This may also pull in some other dependencies.

**Comment by msiemens** [comment]
@amedee, thanks for reporting this! I hope the instructions are more clear now.
