### ISSUE TITLE
Strange output on Windows

### ISSUE THREAD

**Issue by itavero** [msiemens/PyGitUp#24]
I'm getting the following output on Windows (both in Command Prompt, as well as in Git Bash). Looks like I'm missing something?

```
F←[0me←[0mt←[0mc←[0mh←[0mi←[0mn←[0mg←[0m ←[0mo←[0mr←[0mi←[0mg←[0mi←[0mn←[0m
←[0m←[0m←[1mdevelop     ←[0m←[0m ←[0m←[32mup to date←[0m←[0m
←[0mfeature/528 ←[0m←[0m ←[0m←[32mup to date←[0m←[0m
←[0mfeature/551 ←[0m←[0m ←[0m←[32mup to date←[0m←[0m
←[0mfeature/575 ←[0m←[0m ←[0m←[32mup to date←[0m←[0m
←[0mhotfix/545  ←[0m←[0m ←[0m←[32mup to date←[0m←[0m
←[0mhotfix/580  ←[0m←[0m ←[0m←[32mup to date←[0m←[0m
←[0mThe system cannot find the path specified.
←[0m
```

**Comment by msiemens** [comment]
Strange... Which version of Windows are you using? And which version of PyGitUp?

**Comment by itavero** [comment]
I'm using Windows 7 (x64, Service Pack 1), with Python 2.7.8. GitUp is at version v1.3.0.

**Comment by pampersrocker** [comment]
Same Problem
* Windows 8.1
* Cygwin 64
* Oh-My-Zsh
* Python 3.4.3
* PyGitUp 1.3.0

**Comment by msiemens** [comment]
I can now reproduce this behaviour. Will investigate...

**Comment by msiemens** [comment]
Looks like it's a regression of some kind in [colorama](https://gitub.com/tartley/colorama) introduced in tartley/colorama@961428e6c1c3a6855da5dedccfc418f295b54c25. I'm not sure what the right fix is here (besides downgrading the dependency). Could you both run `echo %TERM%` in your consoles and report the result here?

**Comment by pampersrocker** [comment]
So, hmm as I'm running this on cygwin `%TERM%` does not work, however `echo $TERM` returns `cygwin` on the default windows command line `TERM` is not set:
![image](https://cloud.githubusercontent.com/assets/1851043/7168666/77e5d4c6-e3bf-11e4-83a6-6152926d71d3.png)
![image](https://cloud.githubusercontent.com/assets/1851043/7168686/96aaac7e-e3bf-11e4-94dd-30193ff59d55.png)

**Comment by msiemens** [comment]
For now we'll have to live with a workaround. Could you try the latest dev version (`pip install git+https://github.com/msiemens/PyGitUp.git`) and report whether it actually fixes the bug?

**Comment by Predelnik** [comment]
It seems like it's still the same for me with dev version, also I suggest to add an option to disable coloring entirely since it would be useful not only in that case but to help users annoyed by colors :smile:

**Comment by msiemens** [comment]
Okay, this is getting really interesting. For reference, the latest dev version fixed this on my computer.

@Predelnik Could you uninstall PyGitUp and then reinstall the dev version to make sure?

**Comment by Predelnik** [comment]
Yeah reinstalling seems to fix this issue, I'm not very active user of pip so didn't know that it may be required sorry.

Though there's some leftover `←[0m` at the bottom I don't know if it's intended
![image](https://cloud.githubusercontent.com/assets/2133957/7203928/15ae4248-e527-11e4-80b8-b43b0cc12b58.png)

**Comment by msiemens** [comment]
Yeah, I noticed the `←[0m` too. Will investigate this soon.

**Comment by msiemens** [comment]
I've filed an issue in colorama (which is responsible for converting ANSI codes to Win32 calls): tartley/colorama#49

**Comment by pampersrocker** [comment]
(Just for info you need to add `--upgrade` to the pip call to update the existing version. Instead of manually uninstalling)

Yes I can confirm the the latest dev version fixes the colors, just as @Predelnik said the `←[0m` is left.

**Comment by msiemens** [comment]
Is that still an issue with PyGitUp 1.4.0?

**Comment by hugovk** [comment]
Looks fixed for me: cmd.exe and MINGW32 are much improved and have switched the `[0m←` stuff for colours.

But Git Bash (MINGW64) has lost its colours. I've made a new issue for this different problem: #48.

**Comment by msiemens** [comment]
Okay, we'll track that on the issue you've opened.
