### ISSUE TITLE
Color codes do not work in powershell

### ISSUE THREAD

**Issue by RedX2501** [msiemens/PyGitUp#30]
When trying to use git-up in powershell the color codes do not work:

![2015-07-14_09-48-11](https://cloud.githubusercontent.com/assets/929932/8668645/b0fbf436-2a0d-11e5-9b1b-7be0179a3f4a.png)

Powershell version 4.0

**Comment by msiemens** [comment]
This is propably due to tartley/colorama#48

**Comment by valentijnscholten** [comment]
Same here, clean install of git up today (1.3.0).

**Comment by hugovk** [comment]
https://github.com/tartley/colorama/issues/48 has been fixed, just awaiting a new release from them.

In the meantime, you can either install PyGitUp with colorama==0.3.2, or install the dev version of colorama:
```
git clone https://github.com/tartley/colorama.git
cd colorama
python setup.py develop
git up
```

**Comment by msiemens** [comment]
In PyGitUp v1.4.0 the dependencies have been updated. This should be fixed now.
