### ISSUE TITLE
When git is not in path it prints an unrelated message

### ISSUE THREAD

**Issue by RedX2501** [msiemens/PyGitUp#32]
Under windows i don't have git in my PATH by default. Executing git-up in those situations prints 
> We don't seem to be in a git repository.

although i'm in a repo.

It would be nicer if it was more specific.

**Comment by msiemens** [comment]
In the next release, PyGitUp will report a better message when git is not in the PATH :)

Unfortunately fixing this required either to drop Python 2.6 support or duplicate a bunch of code. I decided to go with the first option as I didn't specify in the README which versions of Python 2 are supported (this is now fixed, too).
