### ISSUE TITLE
Colours missing in Git Bash (MINGW64)

### ISSUE THREAD

**Issue by hugovk** [msiemens/PyGitUp#48]
- Windows 7
- Python 2.7.9

---

Git Bash (MINGW64) terminal had colours in the last release, but not in this:

PyGitUp 1.3.0:
![image](https://cloud.githubusercontent.com/assets/1324225/13395270/71a102ec-def6-11e5-8078-949f32e5fcf5.png)

PyGitUp 1.4.0:
![image](https://cloud.githubusercontent.com/assets/1324225/13395302/ab876ef6-def6-11e5-81d7-cc641db81864.png)

---

cmd.exe is improved:

PyGitUp 1.3.0:
![image](https://cloud.githubusercontent.com/assets/1324225/13395362/fff74ea2-def6-11e5-8910-9c9f83d01604.png)

PyGitUp 1.4.0:
![image](https://cloud.githubusercontent.com/assets/1324225/13395348/e8b0adba-def6-11e5-99f3-7790d4cc56c5.png)

---

MINGW32 is improved:

PyGitUp 1.3.0:
![image](https://cloud.githubusercontent.com/assets/1324225/13395410/36bd2b78-def7-11e5-9d15-e496dedfb7ce.png)

PyGitUp 1.4.0:
![image](https://cloud.githubusercontent.com/assets/1324225/13395436/5b62633a-def7-11e5-8144-d9c9d74a9a7a.png)

**Comment by msiemens** [comment]
Good to seee cmd.exe and MinGW32 improved. For Git Bash I suspect it to be the same issue that you already reported in tartley/colorama#77.

**Comment by hugovk** [comment]
Closing this old issue, and I'm no longer using Windows. (But still happily using git-up on Mac. Thank you!)
