### ISSUE TITLE
Distribute tests on release

### ISSUE THREAD

**Issue by FRidh** [msiemens/PyGitUp#51]
The repository includes tests but unfortunately these are not distributed on a release. Packagers are interested in these files because they're often used to test whether the packaged package actually works. On future releases please include the tests. Thanks!
(https://github.com/NixOS/nixpkgs/pull/15751)

**Comment by msiemens** [comment]
PyGitUp v1.4.1 has just been released and includes the tests now :)

**Comment by FRidh** [comment]
Thanks!
