### ISSUE TITLE
Move untracked files

### ISSUE THREAD

**Issue by vovanz** [msiemens/PyGitUp#52]
When `pull` is going to overwrite untracked files `git up` will fail with:

```
error: The following untracked working tree files would be overwritten by checkout
..............
Please move or remove them before you can switch branches.
Aborting
```

I suggest to move them to a temporary directory after performing stashing and get them back after unstashing so you won't have to do it manually.

I understand that such behavior could be kinda confusing so it may be enabled by a specific command line argument (something like `--move-untracked`).

**Comment by msiemens** [comment]
Hey @vovanz, thanks for opening the issue. I think untracked files being overwritten by a checkout should be a very rare case. Whenever this happens, it usually requires investigation which files to keep. Having a flag would encourage users to use it even when it would result in data loss. All in all I don't think that's something PyGitUp should take care of.

What do you think?

**Comment by ekohl** [comment]
As a user I agree with @msiemens that PyGitUp should stay away from my untracked files. I feel much safer that it shows me an error rather than trying to be smart.

**Comment by msiemens** [comment]
Closing as wontfix, I really feel like PyGitUp shouldn't mess with untracked files.
