### ISSUE TITLE
Can't run git up from a subfolder

### ISSUE THREAD

**Issue by swhinnem** [msiemens/PyGitUp#59]
I'm getting a NoSuchPathError when I try to run `git up` when I'm currently in a subfolder of my git project. 

Sanitized snip here: https://gist.github.com/swhinnem/090510b45817bdc4b6db5c341a8b1d6e

Weird thing to note- the final error at the end lists the subfolder I'm in twice in the path.

**Comment by msiemens** [comment]
Interesting. Which version of PyGitUp are you using? Maybe it's a regression in the last release...

**Comment by swhinnem** [comment]
I'm on git-up 1.4.4.

**Comment by msiemens** [comment]
So basically my bugfix to #58 was faulty. I've now fixed the git dir detection logic which should now correctly account for subfolders. Could you verify it works now by installing the latest dev version (`pip install -U git+https://github.com/msiemens/PyGitUp`)?

**Comment by swhinnem** [comment]
So I have to run any pip installs with `--ignore-installed six`, which doesn't work with your git URL, but it did work fine with `--upgrade`. 

Directories are working fine again, thanks!

**Comment by msiemens** [comment]
Awesome, I'm glad it works again :)
