### ISSUE TITLE
can i checkout all branches one by one

### ISSUE THREAD

**Issue by susong7519** [msiemens/PyGitUp#61]

**Comment by msiemens** [comment]
Hey, could you elaborate on what you mean?

**Comment by susong7519** [comment]
There are many branches in the remote, and other colleagues will continue to increase, how do I checkout all the branches to local by one command. Rather than manually checkout one by one.

**Comment by jweede** [comment]
offhand a bash command like this would work:

```
for branch in $(git branch -r); do
  git checkout -t $branch
done
```

**Comment by susong7519** [comment]
It worked,thank you!
