### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by ekohl** [msiemens/PyGitUp#62]
It would be great if a new release was made with the bugfixes present in master. I intend to package this for Fedora and that would save me from shipping patches.

**Comment by msiemens** [comment]
Thanks for bringing this up, somehow I forgot to release the latest changes. Now published as [v1.4.5](https://github.com/msiemens/PyGitUp/releases/tag/v1.4.5) :)

**Comment by ekohl** [comment]
Thanks!
