### ISSUE TITLE
Add `--push` option to `git-up`

### ISSUE THREAD

**Issue by WoLpH** [msiemens/PyGitUp#71]
Half of the times I'll run git-up because I want to push something and want to make sure I'm up to date (as to avoid conflicts). It would be great if I could execute it in 1 command easily and safely

**Comment by msiemens** [comment]
Good idea. Would you like to write a pull request for this?

**Comment by WoLpH** [comment]
Sure, if I get a little time off I create a pull request

**Comment by msiemens** [comment]
By the way, this is closed by #74 :)
