### ISSUE TITLE
git: 'up' is not a git command.

### ISSUE THREAD

**Issue by mountpoint** [msiemens/PyGitUp#88]
I've installed git-up via pip, but here is an error: **git: 'up' is not a git command. See 'git --help'.**

Terminal was restarted an logged out of system

I don't know what to do :)

OS: Debian 9.8
Git version: 2.11.0
Python 3.5.3 (I've tried on 2.7 also)
Shell: Zsh (I've tried in bash also)

Screenshot
![selection_27_02_2019-20 00 13](https://user-images.githubusercontent.com/2649412/53512162-b8d0b080-3aca-11e9-8946-c636e9f0496e.jpg)

**Comment by msiemens** [comment]
Hey @mountpoint! Seems like the `git-up` executable is not in the `$PATH`. Can you run `git-up` directly? If not, you should check if the pip binary path (probably `
~/.local/bin`) is in your `$PATH`

**Comment by mountpoint** [comment]
@msiemens Thanks! I've added `~/.local/bin` to `$PATH` and it works =)

**Comment by msiemens** [comment]
Awesome, thank for letting me know that it worked :)
