### ISSUE TITLE
FYI - Intent to package for Fedora

### ISSUE THREAD

**Issue by mhjacks** [msiemens/PyGitUp#97]
Hello,

I'm a new Fedora packager and I have submitted a Fedora package review request to add PyGitUp to Fedora as git-up, at version 1.6.1; it will be added to at least Fedora 31 and Rawhide (which will become Fedora 32 in time):

https://bugzilla.redhat.com/show_bug.cgi?id=1786724

Thanks for this useful addition to the Python and Git ecosystems.

Please feel free to close this issue to acknowledge this, my contact info is included in the bug report or here on github.

**Comment by msiemens** [comment]
Thanks for letting me know! It's great to hear that PyGitUp is a help to folks out there 🙂
