### ISSUE TITLE
git-up will not fast-forward with git > 2.26 when using rebase

### ISSUE THREAD

**Issue by cesarizu** [msiemens/PyGitUp#98]
Because of a change in git 2.26 (see [mailing list](https://www.spinics.net/lists/git/msg377975.html)), `git-up` will not fast-forward a branch as expected anymore. The solution is to use something like this for the `rebase` command:

`git -c rebase.abbreviateCommands=false rebase`

Or by running:

`git config rebase.abbreviateCommands false`

This breaks the "out of the box" experience with `git-up`. Is this something that should be fixed here?

**Comment by msiemens** [comment]
Hey @cesarizu, thanks for reporting this! The funny thing is that even though I use PyGitUp myself regularly I didn't experience any issues lately. Is it possible that this has been resolved in Git 2.27? There the [changelog states](https://raw.githubusercontent.com/git/git/master/Documentation/RelNotes/2.27.0.txt):

>  * "git rebase" with the merge backend did not work well when the
   rebase.abbreviateCommands configuration was set.
   (merge de9f1d3ef4 ag/rebase-merge-allow-ff-under-abbrev-command later to maint).

**Comment by cesarizu** [comment]
I can confirm that Git 2.27 doesn't need any workaround anymore.
